version: "3.9"
services:
  api:
    build: .
    ports:
      - "47375:47375"
    env_file:
      - .env_422ca5fd-04e6-47e0-a569-9b11c4768453
    depends_on:
      - db
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: gen_8a70b7d29d
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
